### ISSUE TITLE
Can't display local pictures

### ISSUE THREAD

**Issue by richardmazur1** [sykeben/BlueDashPro#2]
**Describe the bug**
I was hoping to display local files for sponsor logos.  It doesn't seem to work.

**To Reproduce**
1. Go to link for page
2. Update information for my team
3. Copy on of the default sponsors to local for testing
4. Modify for local file.  Tried following formats:
file:///c:\myfiles\1.png
C:\myfiles\1.png
file:///c:/myfiles.png

**Expected behavior**
Expecting logo to display as it does for defaults.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 7
 - Browser:chrome
 - Version 71.0.3578.98

**Additional context**

**Comment by sykeben** [comment]
I believe your browser may be blocking JS from accessing local files through the `file://` protocol for security reasons. I cannot fix this as it would require modifying your browser to allow web pages to access local files through the `file://` protocol, which may allow malicious sites to read, and copy, your entire harddisk.

In fact, the JS Sandbox will not allow this at all. Here's an excerpt from the Security section of the JavaScript WikiPedia page:

> "scripts run in a sandbox in which they can only perform Web-related actions, not general-purpose programming tasks like creating files"

[[source]](https://en.wikipedia.org/wiki/JavaScript#Security)

<br>

Sorry about that. You can create a new repository, fill it with your images, and reference the raw image file URLs in the settings page instead. Or, you can upload them to any public image sharing site and reference their raw URLs, too. I would suggest using [imgur](https://imgur.com/) or [imgbox](http://imgbox.com/). The issue, sadly, cannot be fixed be me.
